kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
     smtp_smarthost: smtp.gmail.com:465
     smtp_from: alertmanager@hire.com
     smtp_auth_username: awspractice1999@gmail.com
     smtp_auth_password: 'saeqfawbjvhzbng'
     smtp_require_tls: false
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 30s
      repeat_interval: 1m  
      receiver: mail
    
    receivers:
     - name: 'mail'
       email_configs:
       - to: awspractice1999@gmail.com
         smarthost: smtp.gmail.com:587
         
         send_resolved: true

