apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-local-storage

provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: prometheus-vol

spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-local-storage
  hostPath:
    path: "/opt/k8-disk/prometheus"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-claim

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: prometheus-local-storage
  resources:
    requests:
      storage: 5Gi
