apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume-1
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: 'vol-0caffdbdae0ffe6a5'
    fsType: xfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
resources:
  requests:
    storage: 5i
   selector:
    matchLabels:
      type: data-volume-1
