apiVersion: v1
data:
  config.yml: "global:\n smtp_smarthost: smtp.gmail.com:465\n smtp_from: alertmanager@hire.com\n
    smtp_auth_username: awspractice1999@gmail.com\n smtp_auth_password: 'saeqfawbjvhzbng'\n
    smtp_require_tls: false\ntemplates:\n- '/etc/alertmanager-templates/*.tmpl'\nroute:\n
    \ group_by: ['alertname', 'cluster', 'service']\n  group_wait: 30s\n  group_interval:
    30s\n  repeat_interval: 1m  \n  receiver: mail\n\nreceivers:\n - name: 'mail'\n
    \  email_configs:\n   - to: awspractice1999@gmail.com\n     smarthost: smtp.gmail.com:587\n
    \    \n     send_resolved: true"
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: monitoring

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
  labels:
    name: alertmanager
    
  name: alertmanager
  namespace: monitoring
spec:
  ports:
  - name: alertmanager
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: alertmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
      name: alertmanager
    spec:
      containers:
      - args:
        - --config.file=/etc/alertmanager/config.yml
        - --storage.path=/alertmanager
        image: prom/alertmanager:v0.20.0
        name: alertmanager
        ports:
        - containerPort: 9093
          name: alertmanager
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: config-volume
        - mountPath: /alertmanager
          name: alertmanager
      volumes:
      - configMap:
          name: alertmanager
        name: config-volume
      - emptyDir: {}
        name: alertmanager
