#Need to run this on node which will play worker node in kubernetes cluster
# Also pick the token and cacerthasses from master server /tmp/output-of-init.txt and replace below
# now get complete host name of node:Run this command to get hostname on wordker node and replace below in nodeRegistration: 
# # curl http://169.254.169.254/latest/meta-data/local-hostname
- hosts: all
  become: yes
  tasks: 
   - name: copy node.yml to node /etc/kubernetes/node.yml
     shell:
      cmd: |
       cat <<EOF > /etc/kubernetes/node.yml
       ---
       apiVersion: kubeadm.k8s.io/v1beta1
       kind: JoinConfiguration
       discovery:  
          bootstrapToken:
           token: "cimhi8.zumyfsb2i0q5v1k7"
           apiServerEndpoint: "172.16.1.246:6443"
           caCertHashes:
            - "sha256:025002b2077aa84bf31890eaaf9421b88470f1825a8e2554c147828717bbcf7d"
       nodeRegistration:
         name: ip-172-16-1-151.ap-south-1.compute.internal
         kubeletExtraArgs:
           cloud-provider: aws
       EOF
       
   - name: run kubeadm join command
     shell: kubeadm join --config /etc/kubernetes/node.yml > /tmp/output-of-join.txt
